'use client'

import { Provider } from "jotai";
import "./globals.css";
import { Bonbon, Inter } from "next/font/google";
import {FC, PropsWithChildren, ReactNode} from "react";
import { QueryClient, QueryClientProvider } from "react-query";

//이런 식으 문제가 해결되고 ~, 왜  ReactNode 값을 바로 넣게 되면 에러가 발생하지?

const queryClient = new QueryClient()

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
    <html>
    <body>
    <QueryClientProvider client={queryClient}>
        <Provider>
            {/* <header className='flex justify-between px-40 py-4 bg-white'>
                  <div className='flex items-center gap-4'>
                  ALIVE-MONEY
                  </div>
                  <SideBar/>
            </header>  */}
            <div className="px-40 mx-auto ">

                <div>{children}</div>
            </div>
        </Provider>
    </QueryClientProvider>
    </body>
    </html>
);
export default RootLayout;
